trigger:
  branches:
    include:
      - master
  paths:
    include:
      - linux/*
      - win/*

pr:
  branches:
    include:
      - '*'
  paths:
    include:
      - linux/*
      - win/*

schedules:
  - cron: '0 7 * * *'
    displayName: 'Rebuild images for updates'
    branches:
      include:
        - master
    always: true

variables:
  vmImage: 'ubuntu-latest'

jobs:
  - job: 'lint'
    pool:
      vmImage: $(vmImage)
    steps:
      - script: ./runner lint

  - job: 'build'
    timeoutInMinutes: 600
    condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))
    dependsOn: lint
    pool:
      vmImage: $(vmImage)
    steps:
      - task: UniversalPackages@0
        displayName: 'Universal download'
        inputs:
          command: download
          vstsFeed: 'ukhoget'
          vstsFeedPackage: 'cov-analysis-linux64-2019.12'
          vstsPackageVersion: 2019.12.0
          downloadDirectory: '$(Build.SourcesDirectory)\linux'
      - bash: |
          src='$(Build.SourcesDirectory)/linux/cov-analysis-linux64-2019.12.tar.gz'
          cp ${src} '$(Build.SourcesDirectory)/linux/jdk8-python36-cov/cov-analysis-linux64-2019.12.tar.gz'
          cp ${src} '$(Build.SourcesDirectory)/linux/mvn361-jdk8-cov/cov-analysis-linux64-2019.12.tar.gz'
      - script: ./runner build

  - job: 'publish'
    timeoutInMinutes: 600
    pool:
      vmImage: $(vmImage)
    dependsOn:
      - 'lint'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    steps:
      - script: docker login -u $(DOCKER_REGISTRY_USERNAME) -p $(DOCKER_REGISTRY_PASSWORD)
      - task: UniversalPackages@0
        displayName: 'Universal download'
        inputs:
          command: download
          vstsFeed: 'ukhoget'
          vstsFeedPackage: 'cov-analysis-linux64-2019.12'
          vstsPackageVersion: 2019.12.0
          downloadDirectory: '$(Build.SourcesDirectory)\linux\jdk8-python36-cov'
      - script: ./runner build publish
