trigger: none
pr: none

schedules:
  - cron: 0 23 * * *
    always: true
    branches:
     include:
       - main
    displayName: scheduled database update

pool: Mare Nectaris
variables:
- group: NvdApiKey
- group: dockerhub
steps:
- script: |
    docker build --tag ukhydrographicoffice/dependency-check .
    docker run -rm ukhydrographicoffice/dependency-check --updateonly
  displayName: Build nvd data
  workingDirectory: $(Build.SourcesDirectory)/dependency-check
