trigger:
  branches:
    include:
      - main
  paths:
    include:
      - linux/*

pr:
  branches:
    include:
      - '*'
  paths:
    include:
      - linux/*

schedules:
  - cron: '0 6 * * 1-5'
    displayName: 'Rebuild images for updates'
    branches:
      include:
        - main
    always: true

variables:
  - name: PoolName
    value: "Mare Nectaris"
  - group: dockerhub


jobs:
  - job: 'lint'
    pool: $(PoolName)
    steps:
      - script: ./runner lint

  - job: 'build'
    timeoutInMinutes: 600
    condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/main'))
    dependsOn: lint
    pool: $(PoolName)
    steps:
      - script: ./runner --linux build


  - job: 'publish'
    timeoutInMinutes: 600
    pool: $(PoolName)
    dependsOn:
      - 'lint'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    steps:
      - script: docker login -u $(DOCKER_REGISTRY_USERNAME) -p $(DOCKER_REGISTRY_PASSWORD)     
      - script: ./runner --linux build publish