trigger: none
pr: none

schedules:
  - cron: 0 23 * * *
    always: true
    branches:
     include:
       - main
    displayName: scheduled database update

pool: Mare Nectaris
variables:
- group: NvdApiKey
- group: dockerhub
steps:
- script: |
    export DOCKER_BUILDKIT=1
    echo "$(NvdApiKey)" > nvdapikey.txt 
    docker build --secret id=nvdapikey,src=nvdapikey.txt --tag ukhydrographicoffice/dependency-check .
    docker run --rm ukhydrographicoffice/dependency-check --version
  displayName: Build nvd data
  workingDirectory: $(Build.SourcesDirectory)/dependency-check
- task: Docker@2
  inputs:
    containerRegistry: 'ukho-dockerhub'
    repository: 'ukhydrographicoffice/dependency-check'
    command: 'push'
    tags: 'latest'
