trigger: none
pr: none

schedules:
  - cron: 0 23 * * *
    always: true
    branches:
     include:
       - main
    displayName: scheduled database update

pool: Mare Nectaris
variables:
- group: NvdApiKey
- group: dockerhub
steps:
- script: |
      docker pull owasp/dependency-check:latest
      docker run owasp/dependency-check:latest --updateonly --nvdApiKey $(NvdApiKey)
  displayName: Hydrate NVD database
- script: |
    #!/bin/bash
    # Get the container ID of the most recent running container
    container_id=$(docker ps -qa)
    echo "Container ID: $container_id"
    docker commit $container_id ukhydrographicoffice/dependency-check:latest
    docker ps -a
    docker image ls
  displayName: Create Image
- task: Docker@2
  inputs:
    containerRegistry: 'ukho-dockerhub'
    repository: 'ukhydrographicoffice/dependency-check'
    command: 'push'
    tags: 'latest'
    addPipelineData: false
    addBaseImageData: false
