trigger:
  - master

pr:
  branches:
    include:
      - '*'

schedules:
  - cron: '0 7 * * *'
    displayName: 'Rebuild images for updates'
    branches:
      include:
        - master
    always: true

variables:
  poolName: 'ubuntu-latest'

jobs:
  - job: 'check'
    pool: $(poolName)
    steps:
      - script: make lint

  - job: 'build'
    pool: $(poolName)
    steps:
      - script: make build

  - job: 'publish'
    pool: $(poolName)
    dependsOn:
      - 'lint'
      - 'build'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master')
    steps:
      - script: docker login -u $(DOCKER_REGISTRY_USERNAME) -p $(DOCKER_REGISTRY_PASSWORD)
      - script: make push
