trigger:
  branches:
    include:
      - master
  paths:
    include:
      - linux/*
      - win/*

pr:
  branches:
    include:
      - '*'
  paths:
    include:
      - linux/*
      - win/*

schedules:
  - cron: '0 7 * * *'
    displayName: 'Rebuild images for updates'
    branches:
      include:
        - master
    always: true

variables:
  vmImage: 'ubuntu-latest'

jobs:
  - job: 'lint'
    pool:
      vmImage: $(vmImage)
    steps:
      - script: ./runner lint

  - job: 'build'
    timeoutInMinutes: 600
    dependsOn: lint
    pool:
      vmImage: $(vmImage)
    steps:
      - script: ./runner build

  - job: 'publish'
    timeoutInMinutes: 600
    pool:
      vmImage: $(vmImage)
    dependsOn:
      - 'lint'
      - 'build'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    steps:
      - script: docker login -u $(DOCKER_REGISTRY_USERNAME) -p $(DOCKER_REGISTRY_PASSWORD)
      - script: ./runner build publish
