trigger:
  branches:
    include:
      - main
  paths:
    include:
      - linux/*
      - win/*

pr:
  branches:
    include:
      - '*'
  paths:
    include:
      - linux/*
      - win/*

schedules:
  - cron: '0 6 * * 1-5'
    displayName: 'Rebuild images for updates'
    branches:
      include:
        - main
    always: true

variables:
  PoolName: "UKHO Ubuntu 1804"

jobs:
  - job: 'lint'
    pool: $(PoolName)
    steps:
      - script: ./runner lint

  - job: 'build'
    timeoutInMinutes: 600
    condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/main'))
    dependsOn: lint
    pool: $(PoolName)
    steps:
      - task: UniversalPackages@0
        displayName: 'Universal download'
        inputs:
          command: download
          vstsFeed: 'ukhoget'
          vstsFeedPackage: 'cov-analysis-linux64-2019.12'
          vstsPackageVersion: 2019.12.0
          downloadDirectory: '$(Build.SourcesDirectory)/linux'
      - bash: |
          src='$(Build.SourcesDirectory)/linux/cov-analysis-linux64-2019.12.tar.gz'
          cp ${src} '$(Build.SourcesDirectory)/linux/aardvarkcov/cov-analysis-linux64-2019.12.tar.gz'
      - script: ./runner --linux build

  - job: 'publish'
    timeoutInMinutes: 600
    pool: $(PoolName)
    dependsOn:
      - 'lint'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    steps:
      - script: docker login -u $(DOCKER_REGISTRY_USERNAME) -p $(DOCKER_REGISTRY_PASSWORD)
      - task: UniversalPackages@0
        displayName: 'Universal download'
        inputs:
          command: download
          vstsFeed: 'ukhoget'
          vstsFeedPackage: 'cov-analysis-linux64-2019.12'
          vstsPackageVersion: 2019.12.0
          downloadDirectory: '$(Build.SourcesDirectory)/linux'
      - bash: |
          src='$(Build.SourcesDirectory)/linux/cov-analysis-linux64-2019.12.tar.gz'
          cp ${src} '$(Build.SourcesDirectory)/linux/aardvarkcov/cov-analysis-linux64-2019.12.tar.gz'         
      - script: ./runner --linux build publish
