trigger:
  - master

pr:
  branches:
    include:
      - '*'

schedules:
  - cron: '0 7 * * *'
    displayName: 'Rebuild images for updates'
    branches:
      include:
        - master
    always: true

variables:
  vmImage: 'UKHO Ubuntu 1804'

jobs:
  - job: 'check'
    pool: $(vmImage)
    steps:
      - script: ./runner lint

  - job: 'build'
    dependsOn: check
    pool: $(vmImage)
    steps:
      - script: ./runner build

  - job: 'publish'
    pool: $(vmImage)
    dependsOn:
      - 'check'
      - 'build'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    steps:
      - script: docker login -u $(DOCKER_REGISTRY_USERNAME) -p $(DOCKER_REGISTRY_PASSWORD)
      - script: ./runner publish
