trigger:
  - master

pr:
  branches:
    include:
      - '*'

schedules:
  - cron: '0 7 * * *'
    displayName: 'Rebuild images for updates'
    branches:
      include:
        - master
    always: true

variables:
  vmImage: 'ubuntu-latest'

jobs:
  - job: 'check'
    pool:
      vmImage: $(vmImage)
    steps:
      - script: ./pleasew test

  - job: 'build'
    pool:
      vmImage: $(vmImage)
    steps:
      - script: ./pleasew run //:build

  - job: 'publish'
    pool:
      vmImage: $(vmImage)
    dependsOn:
      - 'check'
      - 'build'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    steps:
      - script: docker login -u $(DOCKER_REGISTRY_USERNAME) -p $(DOCKER_REGISTRY_PASSWORD)
      - script: ./pleasew run //:publish
