package(default_visibility = ["PUBLIC"])

github_repo(
    name = "pleasings",
    repo = "thought-machine/pleasings",
    revision = "9eed1abde1864b1ce70a2a0b5f0682e82cfc607d",
    hashes = ["29f488c668621bc112fec918daaac5607a0620dc"],
)

export_file(
    name = "docker",
    src = "docker.build_defs",
)

export_file(
    name = "sh",
    src = "sh.build_defs",
)
