package(default_visibility = ["PUBLIC"])

remote_file(
    name = "docker",
    url = "https://raw.githubusercontent.com/thought-machine/pleasings/9eed1abde1864b1ce70a2a0b5f0682e82cfc607d/docker/docker.build_defs",
    hashes = [
        "708a9d2a9c2df7d7d4c42e5dbfb3e4cfd54e15fd",
    ],
)

export_file(
    name = "sh",
    src = "sh.build_defs"
)
